INSERT INTO restaurant_categories_has_restaurants (id, restaurant_category_id, restaurant_id, created_at, updated_at)
VALUES
    (1, 1, 1, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'),
    (2, 3, 1, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'),
    (3, 2, 2, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'),
    (4, 4, 2, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'),
    (5, 3, 3, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'),
    (6, 5, 3, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'),
    (7, 2, 4, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'),
    (8, 4, 4, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'),
    (9, 3, 5, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'),
    (10, 5, 5, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'),
    (11, 1, 6, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'),
    (12, 2, 6, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'),
    (13, 4, 7, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'),
    (14, 5, 7, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'),
    (15, 1, 8, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'),
    (16, 5, 8, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'),
    (17, 1, 9, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'),
    (18, 5, 9, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'),
    (19, 3, 10, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'),
    (20, 5, 10, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'),
    (21, 4, 11, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC'),
    (22, 6, 11, NOW() AT TIME ZONE 'UTC', NOW() AT TIME ZONE 'UTC')
