// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: copyfrom.go

package database

import (
	"context"
)

// iteratorForBulkInsertFoodItemsOrders implements pgx.CopyFromSource.
type iteratorForBulkInsertFoodItemsOrders struct {
	rows                 []BulkInsertFoodItemsOrdersParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkInsertFoodItemsOrders) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkInsertFoodItemsOrders) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].FoodItemID,
		r.rows[0].OrderID,
		r.rows[0].Quantity,
	}, nil
}

func (r iteratorForBulkInsertFoodItemsOrders) Err() error {
	return nil
}

func (q *Queries) BulkInsertFoodItemsOrders(ctx context.Context, arg []BulkInsertFoodItemsOrdersParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"food_items_has_orders"}, []string{"food_item_id", "order_id", "quantity"}, &iteratorForBulkInsertFoodItemsOrders{rows: arg})
}
