// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: food_item_has_orders.sql

package database

type BulkInsertFoodItemsOrdersParams struct {
	FoodItemID int64
	OrderID    int64
	Quantity   int32
}
