// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"
)

type FoodCategory struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type FoodItem struct {
	ID             int64
	Name           string
	ImageUrl       string
	Description    string
	Price          string
	RestaurantID   int64
	FoodCategoryID int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Restaurant struct {
	ID            int64
	Name          string
	ImageUrl      string
	AverageRating string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type RestaurantCategoriesHasRestaurant struct {
	ID                   int64
	RestaurantCategoryID int64
	RestaurantID         int64
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type RestaurantCategory struct {
	ID        int64
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID             int64
	Fullname       string
	Email          string
	Hashedpassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
